# Site settings
title: 無聊男子的自言自語
description: 音樂記錄 · 心得 · 生活紀錄
author: tediousman
url: "https://tediousman.github.io"
baseurl: ""
lang: zh-TW

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 10

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Collections / Categories
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics 4
google_analytics: G-3HQTYZDSB3

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
